export const GET_NOVELS_REQUEST='GET_NOVELS_REQUEST'
export const GET_NOVELS_SUCCESS='GET_NOVELS_SUCCESS'
export const GET_NOVELS_FAILURE='GET_NOVELS_FAILURE'

export const ADD_CART_DATA_REQUEST ='ADD_CART_DATA_REQUEST'
export const ADD_CART_DATA_SUCCESS ='ADD_CART_DATA_SUCCESS'
export const ADD_CART_DATA_FAILURE ='ADD_CART_DATA_FAILURE'

export const FETCH_CART_SUCCESS='FETCH_CART_SUCCESS'